/**
 * Permanent redirects: legacy WordPress lava-sa.co.za URL paths → lava-sa.com.
 * Generated by scripts/generate-legacy-co-za-redirects.mjs — re-run after sitemap changes.
 * Last generated: 2026-07-10
 */

export type LegacyRedirect = {
  source: string;
  destination: string;
  permanent: boolean;
};

export const LEGACY_CO_ZA_REDIRECTS: LegacyRedirect[] = [
  {
    "source": "/need-advice/advice-what-does-vacuum-packing-do-or-how-vacuum-packing-works.html",
    "destination": "/vacuum-packaging/advantages",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-which-is-the-best-vacuum-packing-machine-for-my-needs.html",
    "destination": "/guides/vacuum-sealer-buying-guide",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-using-stainless-steel-and-acrylic-vacuum-containers.html",
    "destination": "/products/containers-lids",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-what-does-vacuum-packing-do-or-how-vacuum-packing-works",
    "destination": "/vacuum-packaging/advantages",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-how-to-look-after-your-lava-vacuum-packing-machine.html",
    "destination": "/help/warranty",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-which-is-the-best-vacuum-packing-machine-for-my-needs",
    "destination": "/guides/vacuum-sealer-buying-guide",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-using-stainless-steel-and-acrylic-vacuum-containers",
    "destination": "/products/containers-lids",
    "permanent": true
  },
  {
    "source": "/product/lava-v300-premium-black-limited-edition-vacuum-packing-machine",
    "destination": "/products/v300-black",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-how-to-look-after-your-lava-vacuum-packing-machine",
    "destination": "/help/warranty",
    "permanent": true
  },
  {
    "source": "/downloads/lava-vacuum-sealer-v300-black-limited-edition-user-manual",
    "destination": "/manuals/v300-series",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-guidelines-for-vacuum-packing-cooked-meat.html",
    "destination": "/vacuum-packaging/shelf-life-chart",
    "permanent": true
  },
  {
    "source": "/product/lava-top-vacuum-universal-acrylic-lids-size-27-238-280mm",
    "destination": "/products/acrylic-container-lid-238-280mm",
    "permanent": true
  },
  {
    "source": "/product/lava-top-vacuum-universal-acrylic-lids-size-23-204-237mm",
    "destination": "/products/acrylic-container-lid-204-237mm",
    "permanent": true
  },
  {
    "source": "/product/lava-top-vacuum-universal-acrylic-lids-size-20-160-203mm",
    "destination": "/products/acrylic-container-lid-160-203mm",
    "permanent": true
  },
  {
    "source": "/product/vacuum-sealer-attachment-for-glass-jars-8-9-cm-diameter",
    "destination": "/products/vacuum-sealer-attachment-for-glass-jars-8-9-cm-diameter",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-using-continues-vacuum-packing-rolls.html",
    "destination": "/vacuum-packaging/bags-guide",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-guidelines-for-vacuum-packing-cooked-meat",
    "destination": "/vacuum-packaging/shelf-life-chart",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-vacuum-sealing-caps-for-wine-bottles.html",
    "destination": "/products/acrylic-lids",
    "permanent": true
  },
  {
    "source": "/downloads/lava-vacuum-sealer-v500-premium-121-cm-user-manual",
    "destination": "/manuals/v300-series",
    "permanent": true
  },
  {
    "source": "/product/replacement-lava-sealing-strip-for-v100-v300-premium",
    "destination": "/products/sealing-strips",
    "permanent": true
  },
  {
    "source": "/downloads/lava-vacuum-sealer-v333-black-edition-user-manual",
    "destination": "/manuals/v300-series",
    "permanent": true
  },
  {
    "source": "/downloads/lava-vacuum-sealer-v500-premium-72-cm-user-manual",
    "destination": "/manuals/v300-series",
    "permanent": true
  },
  {
    "source": "/product/gold-black-salmon-boards-21x57cm-pack-of-5-boards",
    "destination": "/products/salmon-board-21x57cm-pack-5",
    "permanent": true
  },
  {
    "source": "/product/replacement-liquid-trap-lid-v400-and-v500-premium",
    "destination": "/products/liquid-trap-lids",
    "permanent": true
  },
  {
    "source": "/product/replacement-liquid-trap-lid-v400-and-v500-classic",
    "destination": "/products/liquid-trap-lids",
    "permanent": true
  },
  {
    "source": "/product/replacement-liquid-trap-lid-v100-classic-premium",
    "destination": "/products/liquid-trap-lids",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-using-continues-vacuum-packing-rolls",
    "destination": "/vacuum-packaging/bags-guide",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-vacuum-sealing-caps-for-wine-bottles",
    "destination": "/products/acrylic-lids",
    "permanent": true
  },
  {
    "source": "/product/lava-v500-premium-121-cm-vacuum-packing-machine",
    "destination": "/products/v500-premium-xxl",
    "permanent": true
  },
  {
    "source": "/product/replacement-lava-sealing-strip-for-v400-premium",
    "destination": "/products/sealing-strips",
    "permanent": true
  },
  {
    "source": "/product/replacement-lava-sealing-strip-for-v500-premium",
    "destination": "/products/sealing-strips",
    "permanent": true
  },
  {
    "source": "/downloads/landig-pro-star-meat-mincer-90kg-user-manual",
    "destination": "/products/butchery-machinery",
    "permanent": true
  },
  {
    "source": "/product/lava-v500-premium-72-cm-vacuum-packing-machine",
    "destination": "/products/v500-premium",
    "permanent": true
  },
  {
    "source": "/downloads/lava-vacuum-sealer-v300-premium-user-manual",
    "destination": "/manuals/v300-series",
    "permanent": true
  },
  {
    "source": "/downloads/lava-vacuum-sealer-v400-premium-user-manual",
    "destination": "/manuals/v300-series",
    "permanent": true
  },
  {
    "source": "/downloads/lava-vacuum-sealer-v100-premium-user-manual",
    "destination": "/manuals/v100-premium-x",
    "permanent": true
  },
  {
    "source": "/downloads/lava-vacuum-sealer-v100-classic-user-manual",
    "destination": "/manuals/v100-premium-x",
    "permanent": true
  },
  {
    "source": "/product/replacement-vacuum-seals-for-v100-v300-range",
    "destination": "/products/vacuum-seals",
    "permanent": true
  },
  {
    "source": "/product/new-line-vacuum-container-rectangular-1200ml",
    "destination": "/products/acrylic-container-1200ml-square",
    "permanent": true
  },
  {
    "source": "/product/new-line-vacuum-container-rectangular-2000ml",
    "destination": "/products/acrylic-container-2000ml-square",
    "permanent": true
  },
  {
    "source": "/product/new-line-vacuum-container-rectangular-1650ml",
    "destination": "/products/acrylic-container-1650ml-rectangular",
    "permanent": true
  },
  {
    "source": "/product/glass-vacuum-container-1520ml-with-handpump",
    "destination": "/products/glass-vacuum-container-1520ml",
    "permanent": true
  },
  {
    "source": "/product/new-line-vacuum-container-rectangular-650ml",
    "destination": "/products/acrylic-container-650ml-square",
    "permanent": true
  },
  {
    "source": "/product/sausage-filler-machine-6-8l-stainless-steel",
    "destination": "/products/commercial-sausage-filler-6-8l-stainless-steel",
    "permanent": true
  },
  {
    "source": "/product/lava-v100-premium-x-vacuum-sealing-machine",
    "destination": "/products/v100-premium-x",
    "permanent": true
  },
  {
    "source": "/product/lava-v300-premium-x-vacuum-packing-machine",
    "destination": "/products/v300-premium-x",
    "permanent": true
  },
  {
    "source": "/product/stainless-steel-es-line-vacuum-bowl-2500ml",
    "destination": "/products/es-line-stainless-container-2500ml",
    "permanent": true
  },
  {
    "source": "/product/stainless-steel-es-line-vacuum-bowl-4000ml",
    "destination": "/products/es-line-stainless-container-4000ml",
    "permanent": true
  },
  {
    "source": "/product/stainless-steel-es-line-vacuum-bowl-1300ml",
    "destination": "/products/es-line-stainless-container-1300ml",
    "permanent": true
  },
  {
    "source": "/product/13-x-22-5-cm-50-bags-embossed-vacuum-bags",
    "destination": "/products/13-x-22-5-cm-50-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/sausage-filler-machine-3l-stainless-steel",
    "destination": "/products/professional-sausage-filler-3l-stainless-steel",
    "permanent": true
  },
  {
    "source": "/product/replacement-vacuum-seals-for-v400-classic",
    "destination": "/products/vacuum-seals",
    "permanent": true
  },
  {
    "source": "/product/replacement-vacuum-seals-for-v400-premium",
    "destination": "/products/vacuum-seals",
    "permanent": true
  },
  {
    "source": "/downloads/lava-vacuum-packaging-comparison-chart",
    "destination": "/products/vacuum-machines",
    "permanent": true
  },
  {
    "source": "/product/70-x-100-cm-10-bags-embossed-vacuum-bags",
    "destination": "/products/70-x-100-cm-10-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/lava-v400-premium-vacuum-packing-machine",
    "destination": "/products/v400-premium",
    "permanent": true
  },
  {
    "source": "/product/lava-v100-premium-vacuum-packing-machine",
    "destination": "/products/v100-premium",
    "permanent": true
  },
  {
    "source": "/product/3-piece-butchers-knife-set-yellow-handle",
    "destination": "/products/butcher-knife-set-yellow-3pc",
    "permanent": true
  },
  {
    "source": "/product/30-x-40-cm-50-bags-embossed-vacuum-bags",
    "destination": "/products/30-x-40-cm-50-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/25-x-40-cm-50-bags-embossed-vacuum-bags",
    "destination": "/products/25-x-40-cm-50-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/15-x-45-cm-50-bags-embossed-vacuum-bags",
    "destination": "/products/15-x-45-cm-50-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/25-x-35-cm-50-bags-embossed-vacuum-bags",
    "destination": "/products/25-x-35-cm-50-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/35-x-50-cm-50-bags-embossed-vacuum-bags",
    "destination": "/products/35-x-50-cm-50-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/20-x-30-cm-50-bags-embossed-vacuum-bags",
    "destination": "/products/20-x-30-cm-50-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/40-x-60-cm-50-bags-embossed-vacuum-bags",
    "destination": "/products/40-x-60-cm-50-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/60-x-80-cm-10-bags-embossed-vacuum-bags",
    "destination": "/products/60-x-80-cm-10-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/16-x-25-cm-50-bags-embossed-vacuum-bags",
    "destination": "/products/16-x-25-cm-50-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/30-x-50-cm-50-bags-embossed-vacuum-bags",
    "destination": "/products/30-x-50-cm-50-bags-embossed-vacuum-bags",
    "permanent": true
  },
  {
    "source": "/product/replacement-lava-sealing-strip-for-v400",
    "destination": "/products/sealing-strips",
    "permanent": true
  },
  {
    "source": "/product/replacement-lava-sealing-strip-for-v500",
    "destination": "/products/sealing-strips",
    "permanent": true
  },
  {
    "source": "/product/yellow-handle-skinner-knife-16cm-blade",
    "destination": "/products/skinner-knife-16cm-yellow",
    "permanent": true
  },
  {
    "source": "/downloads/a-practical-guide-to-vacuum-packing",
    "destination": "/vacuum-packaging",
    "permanent": true
  },
  {
    "source": "/product/4-x-15-cm-x-6-m-embossed-vacuum-rolls",
    "destination": "/products/embossed-vacuum-rolls-15cm-6m-4pack",
    "permanent": true
  },
  {
    "source": "/product/2-x-20-cm-x-6-m-embossed-vacuum-rolls",
    "destination": "/products/embossed-vacuum-rolls-20cm-6m-2pack",
    "permanent": true
  },
  {
    "source": "/product/2-x-30-cm-x-6-m-embossed-vacuum-rolls",
    "destination": "/products/embossed-vacuum-rolls-30cm-6m-2pack",
    "permanent": true
  },
  {
    "source": "/product/stainless-steel-swivel-hooks-300x12mm",
    "destination": "/products/swivel-hooks-300x12mm-200kg",
    "permanent": true
  },
  {
    "source": "/product/stainless-steel-swivel-hooks-260x10mm",
    "destination": "/products/swivel-hooks-260x10mm-150kg",
    "permanent": true
  },
  {
    "source": "/product/cutting-board-scraper-stainless-steel",
    "destination": "/products/cutting-board-scraper-stainless-steel",
    "permanent": true
  },
  {
    "source": "/product/stainless-steel-swivel-hooks-500x12mm",
    "destination": "/products/xl-swivel-hooks-500x12mm-250kg",
    "permanent": true
  },
  {
    "source": "/product/2-x-60-cm-x-6-m-embossed-vacuum-rolls",
    "destination": "/products/embossed-vacuum-rolls-30cm-6m-2pack",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-vacuum-packing-fruit.html",
    "destination": "/vacuum-packaging/expert-tips",
    "permanent": true
  },
  {
    "source": "/product/4-piece-acrylic-vacuum-container-set",
    "destination": "/products/acrylic-container-set-4-piece",
    "permanent": true
  },
  {
    "source": "/product/gold-black-salmon-boards-18-5x53cm",
    "destination": "/products/salmon-board-18x53cm-pack-5",
    "permanent": true
  },
  {
    "source": "/product/gold-black-salmon-boards-12x26-5cm",
    "destination": "/products/salmon-board-12x26-5cm-pack-5",
    "permanent": true
  },
  {
    "source": "/product/replacement-vacuum-seals-for-v500",
    "destination": "/products/vacuum-seals",
    "permanent": true
  },
  {
    "source": "/product/stainless-steel-vacuum-containers",
    "destination": "/products/stainless-containers",
    "permanent": true
  },
  {
    "source": "/product/knife-sharpening-steel-round-10cm",
    "destination": "/products/sharpening-steel-10cm",
    "permanent": true
  },
  {
    "source": "/product/knife-sharpening-steel-round-30cm",
    "destination": "/products/sharpening-steel-30cm",
    "permanent": true
  },
  {
    "source": "/product/replacement-vacuum-seals-for-v333",
    "destination": "/products/vacuum-seals",
    "permanent": true
  },
  {
    "source": "/downloads/lava-digiscale-300-user-manual",
    "destination": "/products/butchery-scales",
    "permanent": true
  },
  {
    "source": "/product/magnetic-knife-board-holder-30cm",
    "destination": "/products/magnetic-knife-holder-30cm",
    "permanent": true
  },
  {
    "source": "/product/magnetic-knife-board-holder-60cm",
    "destination": "/products/magnetic-knife-board-60cm",
    "permanent": true
  },
  {
    "source": "/product/stainless-steel-s-hooks-300x12mm",
    "destination": "/products/s-hooks-300x12mm-200kg",
    "permanent": true
  },
  {
    "source": "/need-advice/advice-vacuum-packing-fruit",
    "destination": "/vacuum-packaging/expert-tips",
    "permanent": true
  },
  {
    "source": "/product/stainless-steel-s-hooks-200x9mm",
    "destination": "/products/s-hooks-200x9mm-125kg",
    "permanent": true
  },
  {
    "source": "/product/stainless-steel-s-hooks-160x6mm",
    "destination": "/products/s-hooks-160x6mm-60kg",
    "permanent": true
  },
  {
    "source": "/product/stainless-steel-s-hooks-160x8mm",
    "destination": "/products/s-hooks-160x8mm-100kg",
    "permanent": true
  },
  {
    "source": "/product/adjustable-gambrel-large-810mm",
    "destination": "/products/gambrel-adjustable-810mm",
    "permanent": true
  },
  {
    "source": "/product/platform-table-top-scale-15kg",
    "destination": "/products/platform-scale-15kg",
    "permanent": true
  },
  {
    "source": "/product/universal-vacuum-acrylic-lids",
    "destination": "/products/acrylic-lids",
    "permanent": true
  },
  {
    "source": "/product/platform-table-top-scale-60kg",
    "destination": "/products/platform-scale-60kg",
    "permanent": true
  },
  {
    "source": "/product/lava-labels-permanent-marker",
    "destination": "/products/lava-labels-and-marker",
    "permanent": true
  },
  {
    "source": "/product/embossed-vacuum-packing-bags",
    "destination": "/products/vacuum-bags",
    "permanent": true
  },
  {
    "source": "/comparing-vacuum-vs-non-vacuum.html",
    "destination": "/vacuum-packaging/advantages",
    "permanent": true
  },
  {
    "source": "/product/manual-hanging-scale-200kg",
    "destination": "/products/hanging-scale-200kg",
    "permanent": true
  },
  {
    "source": "/product/giesser-gutting-knife-16cm",
    "destination": "/products/giesser-gutting-knife-16cm",
    "permanent": true
  },
  {
    "source": "/product/manual-hanging-scale-100kg",
    "destination": "/products/hanging-scale-100kg",
    "permanent": true
  },
  {
    "source": "/lava-sa-terms-and-conditions.html",
    "destination": "/legal/terms",
    "permanent": true
  },
  {
    "source": "/product/pro-star-meat-mincer-90kg",
    "destination": "/products/pro-star-meat-mincer-90kg",
    "permanent": true
  },
  {
    "source": "/pages/lava-vacuum-sealer-v-300-x",
    "destination": "/lp/v300-premium-x",
    "permanent": true
  },
  {
    "source": "/product/cutting-knife-18cm-blade",
    "destination": "/products/cutting-knife-18cm-blade",
    "permanent": true
  },
  {
    "source": "/product/cutting-knife-21cm-blade",
    "destination": "/products/cutting-knife-21cm-blade",
    "permanent": true
  },
  {
    "source": "/product/lava-v300-premium-white",
    "destination": "/products/v300-white",
    "permanent": true
  },
  {
    "source": "/product/boning-knife-13cm-blade",
    "destination": "/products/boning-knife-13cm-blade",
    "permanent": true
  },
  {
    "source": "/product/round-vacuum-containers",
    "destination": "/products/glass-containers",
    "permanent": true
  },
  {
    "source": "/comparing-vacuum-vs-non-vacuum",
    "destination": "/vacuum-packaging/advantages",
    "permanent": true
  },
  {
    "source": "/product/electronic-scale-300kg",
    "destination": "/products/digital-hanging-scale-300kg",
    "permanent": true
  },
  {
    "source": "/product/embossed-vacuum-rolls",
    "destination": "/products/vacuum-rolls",
    "permanent": true
  },
  {
    "source": "/lava-sa-terms-and-conditions",
    "destination": "/legal/terms",
    "permanent": true
  },
  {
    "source": "/product/lava-flex-jar-sealer",
    "destination": "/products/lava-flex-sealer-for-jars",
    "permanent": true
  },
  {
    "source": "/product/apron-l120cm-x-w80cm",
    "destination": "/products/butchers-apron-pvc-120x80cm",
    "permanent": true
  },
  {
    "source": "/product/gambrel-small-560mm",
    "destination": "/products/gambrel-small-560mm",
    "permanent": true
  },
  {
    "source": "/shipping-and-returns.html",
    "destination": "/legal/shipping-returns",
    "permanent": true
  },
  {
    "source": "/conditions-of-use.html",
    "destination": "/legal/conditions",
    "permanent": true
  },
  {
    "source": "/shipping-and-returns",
    "destination": "/legal/shipping-returns",
    "permanent": true
  },
  {
    "source": "/important-links.html",
    "destination": "/help/faq",
    "permanent": true
  },
  {
    "source": "/product/bone-crusher",
    "destination": "/products/bone-crusher-rib-cutter",
    "permanent": true
  },
  {
    "source": "/privacy-notice.html",
    "destination": "/legal/privacy",
    "permanent": true
  },
  {
    "source": "/owner-manuals.html",
    "destination": "/manuals/v300-series",
    "permanent": true
  },
  {
    "source": "/my-account-2.html",
    "destination": "/account/login",
    "permanent": true
  },
  {
    "source": "/conditions-of-use",
    "destination": "/legal/conditions",
    "permanent": true
  },
  {
    "source": "/self-service.html",
    "destination": "/help/faq",
    "permanent": true
  },
  {
    "source": "/need-advice.html",
    "destination": "/vacuum-packaging",
    "permanent": true
  },
  {
    "source": "/contact-us.html",
    "destination": "/contact",
    "permanent": true
  },
  {
    "source": "/my-account.html",
    "destination": "/account/login",
    "permanent": true
  },
  {
    "source": "/checkout-2.html",
    "destination": "/checkout",
    "permanent": true
  },
  {
    "source": "/checkout-3.html",
    "destination": "/checkout",
    "permanent": true
  },
  {
    "source": "/important-links",
    "destination": "/help/faq",
    "permanent": true
  },
  {
    "source": "/privacy-notice",
    "destination": "/legal/privacy",
    "permanent": true
  },
  {
    "source": "/checkout.html",
    "destination": "/checkout",
    "permanent": true
  },
  {
    "source": "/owner-manuals",
    "destination": "/manuals/v300-series",
    "permanent": true
  },
  {
    "source": "/partners.html",
    "destination": "/about",
    "permanent": true
  },
  {
    "source": "/lava-tv.html",
    "destination": "/lava-tv",
    "permanent": true
  },
  {
    "source": "/contact.html",
    "destination": "/contact",
    "permanent": true
  },
  {
    "source": "/my-account-2",
    "destination": "/account/login",
    "permanent": true
  },
  {
    "source": "/self-service",
    "destination": "/help/faq",
    "permanent": true
  },
  {
    "source": "/shop-2.html",
    "destination": "/products/vacuum-machines",
    "permanent": true
  },
  {
    "source": "/cart-2.html",
    "destination": "/checkout",
    "permanent": true
  },
  {
    "source": "/videos.html",
    "destination": "/lava-tv",
    "permanent": true
  },
  {
    "source": "/need-advice",
    "destination": "/vacuum-packaging",
    "permanent": true
  },
  {
    "source": "/contact-us",
    "destination": "/contact",
    "permanent": true
  },
  {
    "source": "/my-account",
    "destination": "/account/login",
    "permanent": true
  },
  {
    "source": "/checkout-2",
    "destination": "/checkout",
    "permanent": true
  },
  {
    "source": "/checkout-3",
    "destination": "/checkout",
    "permanent": true
  },
  {
    "source": "/shop.html",
    "destination": "/products/vacuum-machines",
    "permanent": true
  },
  {
    "source": "/cart.html",
    "destination": "/checkout",
    "permanent": true
  },
  {
    "source": "/downloads",
    "destination": "/manuals/v300-series",
    "permanent": true
  },
  {
    "source": "/partners",
    "destination": "/about",
    "permanent": true
  },
  {
    "source": "/shop-2",
    "destination": "/products/vacuum-machines",
    "permanent": true
  },
  {
    "source": "/cart-2",
    "destination": "/checkout",
    "permanent": true
  },
  {
    "source": "/videos",
    "destination": "/lava-tv",
    "permanent": true
  },
  {
    "source": "/shop",
    "destination": "/products/vacuum-machines",
    "permanent": true
  },
  {
    "source": "/cart",
    "destination": "/checkout",
    "permanent": true
  }
];

/** Fallback: same slug when no explicit product rule matched. */
export const LEGACY_WOO_PRODUCT_FALLBACK: LegacyRedirect = {
  source: "/product/:slug",
  destination: "/products/:slug",
  permanent: true,
};
